### ISSUE TITLE
NodeJS Error

### ISSUE THREAD

**Issue by michaeldeborst** [kirilknysh/ov-reporter#8]
Please choose one (**Don't forget to add an appropriate label**):
- [ ] Google Chrome extension
- [x] Command-line interface

**Describe the bug**

When trying to export records via a custom config.json file I get the following error in the CLI:
```
👤   Opening your history...
(node:1843) UnhandledPromiseRejectionWarning: Error: Page crashed!
    at Page._onTargetCrashed (/usr/local/lib/node_modules/ov-reporter-cli/node_modules/puppeteer/lib/Page.js:158:24)
    at CDPSession.<anonymous> (/usr/local/lib/node_modules/ov-reporter-cli/node_modules/puppeteer/lib/Page.js:134:56)
    at CDPSession.emit (events.js:310:20)
    at CDPSession._onMessage (/usr/local/lib/node_modules/ov-reporter-cli/node_modules/puppeteer/lib/Connection.js:232:12)
    at Connection._onMessage (/usr/local/lib/node_modules/ov-reporter-cli/node_modules/puppeteer/lib/Connection.js:119:19)
    at WebSocket.emit (events.js:310:20)
    at Receiver.receiverOnMessage (/usr/local/lib/node_modules/ov-reporter-cli/node_modules/ws/lib/websocket.js:720:20)
    at Receiver.emit (events.js:310:20)
    at Receiver.dataMessage (/usr/local/lib/node_modules/ov-reporter-cli/node_modules/ws/lib/receiver.js:414:14)
    at Receiver.getData (/usr/local/lib/node_modules/ov-reporter-cli/node_modules/ws/lib/receiver.js:346:17)
(node:1843) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1843) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.


💩   Navigation Timeout Exceeded: 30000ms exceeded
```

**To Reproduce**
The command I used was: ovr --config=ovrconfig.json
My ovrconfig looks like this (redacted for privacy reasons):
```
{
    "username": "myusername",
    "password": "mypassword",
    "output": "~/reports",
    "card": "3528************",
    "days": [1, 1, 1, 1, 1, 0, 0],    "month": 3,    "historyUrl": "https://www.ov-chipkaart.nl/mijn-ov-chip/mijn-ov-reishistorie.htm"
}
```

**Expected behavior**
I expect the cli to return a succesful message and to have saved my report in the specified location. 

**Desktop (please complete the following information):**
macOS 10.15.4 Catalina using the terminal

**Comment by kirilknysh** [comment]
Thanks a lot for the report!

Should be fixed in `v1.3.1`, please re-check.
